Product:
  Bag:
    btn_add_to_cart:  //button[@id='add-to-cart-sauce-labs-backpack']
  
  Title:
    txt_title:  //span[text()='Products']

  Cart:
    btn_cart: //a[@class='shopping_cart_link']
    txt_item: //div[text()='Sauce Labs Backpack']
    btn_remove: remove-sauce-labs-backpack